# Generated by Django 3.2 on 2021-04-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Empregado',
        ),
    ]
