# Generated by Django 3.2.4 on 2021-06-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=10)),
                ('contrato', models.CharField(blank=True, choices=[('H', 'Horista'), ('C', 'Comissionado'), ('A', 'Assalariado')], max_length=1)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('sindicato', models.BooleanField(default=False)),
            ],
        ),
    ]
